export interface Pattern {
    id: string;
    name: string;
    category: 'still' | 'oscillator' | 'spaceship' | 'methuselah' | 'gun' | 'square';
    cells: [number, number][];
    width: number;
    height: number;
}

// Helper to generate a filled square of size n
const generateSquare = (n: number): [number, number][] => {
    const cells: [number, number][] = [];
    for (let y = 0; y < n; y++) {
        for (let x = 0; x < n; x++) {
            cells.push([x, y]);
        }
    }
    return cells;
};

export const SQUARE_PATTERNS: Pattern[] = [
    {
        id: 'square3',
        name: '3x3',
        category: 'square',
        cells: generateSquare(3),
        width: 3,
        height: 3,
    },
    {
        id: 'square4',
        name: '4x4',
        category: 'square',
        cells: generateSquare(4),
        width: 4,
        height: 4,
    },
    {
        id: 'square8',
        name: '8x8',
        category: 'square',
        cells: generateSquare(8),
        width: 8,
        height: 8,
    },
    {
        id: 'square16',
        name: '16x16',
        category: 'square',
        cells: generateSquare(16),
        width: 16,
        height: 16,
    },
    {
        id: 'square32',
        name: '32x32',
        category: 'square',
        cells: generateSquare(32),
        width: 32,
        height: 32,
    },
    {
        id: 'square64',
        name: '64x64',
        category: 'square',
        cells: generateSquare(64),
        width: 64,
        height: 64,
    },
];

export const STILL_LIFE_PATTERNS: Pattern[] = [
    {
        id: 'block',
        name: 'Block',
        category: 'still',
        cells: [
            [0, 0],
            [1, 0],
            [0, 1],
            [1, 1],
        ],
        width: 2,
        height: 2,
    },
    {
        id: 'beehive',
        name: 'Beehive',
        category: 'still',
        cells: [
            [1, 0],
            [2, 0],
            [0, 1],
            [3, 1],
            [1, 2],
            [2, 2],
        ],
        width: 4,
        height: 3,
    },
    {
        id: 'loaf',
        name: 'Loaf',
        category: 'still',
        cells: [
            [1, 0],
            [2, 0],
            [0, 1],
            [3, 1],
            [1, 2],
            [3, 2],
            [2, 3],
        ],
        width: 4,
        height: 4,
    },
    {
        id: 'boat',
        name: 'Boat',
        category: 'still',
        cells: [
            [0, 0],
            [1, 0],
            [0, 1],
            [2, 1],
            [1, 2],
        ],
        width: 3,
        height: 3,
    },
    {
        id: 'tub',
        name: 'Tub',
        category: 'still',
        cells: [
            [1, 0],
            [0, 1],
            [2, 1],
            [1, 2],
        ],
        width: 3,
        height: 3,
    },
    {
        id: 'pond',
        name: 'Pond',
        category: 'still',
        cells: [
            [1, 0],
            [2, 0],
            [0, 1],
            [3, 1],
            [0, 2],
            [3, 2],
            [1, 3],
            [2, 3],
        ],
        width: 4,
        height: 4,
    },
    {
        id: 'ship',
        name: 'Ship',
        category: 'still',
        cells: [
            [0, 0],
            [1, 0],
            [0, 1],
            [2, 1],
            [1, 2],
            [2, 2],
        ],
        width: 3,
        height: 3,
    },
    {
        id: 'aircraft_carrier',
        name: 'Aircraft Carrier',
        category: 'still',
        cells: [
            [0, 0],
            [1, 0],
            [0, 1],
            [3, 1],
            [2, 2],
            [3, 2],
        ],
        width: 4,
        height: 3,
    },
    {
        id: 'eater',
        name: 'Eater',
        category: 'still',
        cells: [
            [0, 0],
            [1, 0],
            [0, 1],
            [2, 1],
            [2, 2],
            [2, 3],
            [3, 3],
        ],
        width: 4,
        height: 4,
    },
    {
        id: 'mango',
        name: 'Mango',
        category: 'still',
        cells: [
            [1, 0],
            [2, 0],
            [0, 1],
            [3, 1],
            [0, 2],
            [3, 2],
            [1, 3],
            [2, 3],
        ],
        width: 4,
        height: 4,
    },
    {
        id: 'longboat',
        name: 'Long Boat',
        category: 'still',
        cells: [
            [0, 0],
            [1, 0],
            [0, 1],
            [2, 1],
            [1, 2],
            [3, 2],
            [2, 3],
        ],
        width: 4,
        height: 4,
    },
];

export const OSCILLATOR_PATTERNS: Pattern[] = [
    {
        id: 'blinker',
        name: 'Blinker',
        category: 'oscillator',
        cells: [
            [0, 0],
            [1, 0],
            [2, 0],
        ],
        width: 3,
        height: 1,
    },
    {
        id: 'toad',
        name: 'Toad',
        category: 'oscillator',
        cells: [
            [1, 0],
            [2, 0],
            [3, 0],
            [0, 1],
            [1, 1],
            [2, 1],
        ],
        width: 4,
        height: 2,
    },
    {
        id: 'beacon',
        name: 'Beacon',
        category: 'oscillator',
        cells: [
            [0, 0],
            [1, 0],
            [0, 1],
            [3, 2],
            [2, 3],
            [3, 3],
        ],
        width: 4,
        height: 4,
    },
    {
        id: 'clock',
        name: 'Clock',
        category: 'oscillator',
        cells: [
            [2, 0],
            [0, 1],
            [2, 1],
            [1, 2],
            [3, 2],
            [1, 3],
        ],
        width: 4,
        height: 4,
    },
    {
        id: 'pulsar',
        name: 'Pulsar',
        category: 'oscillator',
        cells: [
            [2, 0],
            [3, 0],
            [4, 0],
            [8, 0],
            [9, 0],
            [10, 0],
            [0, 2],
            [5, 2],
            [7, 2],
            [12, 2],
            [0, 3],
            [5, 3],
            [7, 3],
            [12, 3],
            [0, 4],
            [5, 4],
            [7, 4],
            [12, 4],
            [2, 5],
            [3, 5],
            [4, 5],
            [8, 5],
            [9, 5],
            [10, 5],
            [2, 7],
            [3, 7],
            [4, 7],
            [8, 7],
            [9, 7],
            [10, 7],
            [0, 8],
            [5, 8],
            [7, 8],
            [12, 8],
            [0, 9],
            [5, 9],
            [7, 9],
            [12, 9],
            [0, 10],
            [5, 10],
            [7, 10],
            [12, 10],
            [2, 12],
            [3, 12],
            [4, 12],
            [8, 12],
            [9, 12],
            [10, 12],
        ],
        width: 13,
        height: 13,
    },
    {
        id: 'pentadecathlon',
        name: 'Pentadecathlon',
        category: 'oscillator',
        cells: [
            [1, 0],
            [1, 1],
            [0, 2],
            [2, 2],
            [1, 3],
            [1, 4],
            [1, 5],
            [1, 6],
            [0, 7],
            [2, 7],
            [1, 8],
            [1, 9],
        ],
        width: 3,
        height: 10,
    },
    {
        id: 'figure8',
        name: 'Figure 8',
        category: 'oscillator',
        cells: [
            [0, 0],
            [1, 0],
            [2, 0],
            [0, 1],
            [1, 1],
            [2, 1],
            [0, 2],
            [1, 2],
            [2, 2],
            [3, 3],
            [4, 3],
            [5, 3],
            [3, 4],
            [4, 4],
            [5, 4],
            [3, 5],
            [4, 5],
            [5, 5],
        ],
        width: 6,
        height: 6,
    },
];

export const SPACESHIP_PATTERNS: Pattern[] = [
    {
        id: 'glider',
        name: 'Glider',
        category: 'spaceship',
        cells: [
            [1, 0],
            [2, 1],
            [0, 2],
            [1, 2],
            [2, 2],
        ],
        width: 3,
        height: 3,
    },
    {
        id: 'lwss',
        name: 'LWSS',
        category: 'spaceship',
        cells: [
            [0, 0],
            [3, 0],
            [4, 1],
            [0, 2],
            [4, 2],
            [1, 3],
            [2, 3],
            [3, 3],
            [4, 3],
        ],
        width: 5,
        height: 4,
    },
    {
        id: 'mwss',
        name: 'MWSS',
        category: 'spaceship',
        cells: [
            [2, 0],
            [0, 1],
            [4, 1],
            [5, 2],
            [0, 3],
            [5, 3],
            [1, 4],
            [2, 4],
            [3, 4],
            [4, 4],
            [5, 4],
        ],
        width: 6,
        height: 5,
    },
    {
        id: 'hwss',
        name: 'HWSS',
        category: 'spaceship',
        cells: [
            [2, 0],
            [3, 0],
            [0, 1],
            [5, 1],
            [6, 2],
            [0, 3],
            [6, 3],
            [1, 4],
            [2, 4],
            [3, 4],
            [4, 4],
            [5, 4],
            [6, 4],
        ],
        width: 7,
        height: 5,
    },
];

export const METHUSELAH_PATTERNS: Pattern[] = [
    {
        id: 'rpentomino',
        name: 'R-pentomino',
        category: 'methuselah',
        cells: [
            [1, 0],
            [2, 0],
            [0, 1],
            [1, 1],
            [1, 2],
        ],
        width: 3,
        height: 3,
    },
    {
        id: 'acorn',
        name: 'Acorn',
        category: 'methuselah',
        cells: [
            [1, 0],
            [3, 1],
            [0, 2],
            [1, 2],
            [4, 2],
            [5, 2],
            [6, 2],
        ],
        width: 7,
        height: 3,
    },
    {
        id: 'diehard',
        name: 'Diehard',
        category: 'methuselah',
        cells: [
            [6, 0],
            [0, 1],
            [1, 1],
            [1, 2],
            [5, 2],
            [6, 2],
            [7, 2],
        ],
        width: 8,
        height: 3,
    },
    {
        id: 'bheptomino',
        name: 'B-heptomino',
        category: 'methuselah',
        cells: [
            [0, 0],
            [2, 0],
            [3, 0],
            [0, 1],
            [1, 1],
            [2, 1],
            [1, 2],
        ],
        width: 4,
        height: 3,
    },
    {
        id: 'piheptomino',
        name: 'Pi-heptomino',
        category: 'methuselah',
        cells: [
            [0, 0],
            [1, 0],
            [2, 0],
            [0, 1],
            [2, 1],
            [0, 2],
            [2, 2],
        ],
        width: 3,
        height: 3,
    },
    {
        id: 'rabbits',
        name: 'Rabbits',
        category: 'methuselah',
        cells: [
            [0, 0],
            [4, 0],
            [5, 0],
            [6, 0],
            [0, 1],
            [1, 1],
            [2, 1],
            [5, 1],
            [1, 2],
        ],
        width: 7,
        height: 3,
    },
];

export const GUN_PATTERNS: Pattern[] = [
    {
        id: 'gospergun',
        name: 'Gosper Gun',
        category: 'gun',
        cells: [
            // Left block
            [0, 4],
            [1, 4],
            [0, 5],
            [1, 5],
            // Left part
            [10, 4],
            [10, 5],
            [10, 6],
            [11, 3],
            [11, 7],
            [12, 2],
            [12, 8],
            [13, 2],
            [13, 8],
            [14, 5],
            [15, 3],
            [15, 7],
            [16, 4],
            [16, 5],
            [16, 6],
            [17, 5],
            // Right part
            [20, 2],
            [20, 3],
            [20, 4],
            [21, 2],
            [21, 3],
            [21, 4],
            [22, 1],
            [22, 5],
            [24, 0],
            [24, 1],
            [24, 5],
            [24, 6],
            // Right block
            [34, 2],
            [35, 2],
            [34, 3],
            [35, 3],
        ],
        width: 36,
        height: 9,
    },
];

export const PATTERNS: Pattern[] = [
    ...STILL_LIFE_PATTERNS,
    ...OSCILLATOR_PATTERNS,
    ...SPACESHIP_PATTERNS,
    ...METHUSELAH_PATTERNS,
    ...GUN_PATTERNS,
    ...SQUARE_PATTERNS,
];

export const CATEGORIES = [
    'still',
    'oscillator',
    'spaceship',
    'methuselah',
    'gun',
    'square',
] as const;

export const CATEGORY_LABELS: Record<(typeof CATEGORIES)[number], string> = {
    still: 'Still Lifes',
    oscillator: 'Oscillators',
    spaceship: 'Spaceships',
    methuselah: 'Methuselahs',
    gun: 'Guns',
    square: 'Squares',
};
